# -*- coding: utf-8 -*-
"""Movie Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD-J8bUkBr94TVXM5TYy-BE7ovVUpmoO
"""

import numpy as np
import pandas as pd


movies = pd.read_csv('tmdb_5000_credits.csv')
credits = pd.read_csv('tmdb_5000_movies.csv')

# movies.head(1)
credits.head(1)